### PR TITLE
Add shared import that was missing

### PR DESCRIPTION
**Pull request by Holidayy95**
'@qb-core/import.lua'

### CODE REVIEW

**Comment by Bigbearbeasttv** [comment]
This was removed on purpose.

**Comment by Holidayy95** [comment]
The Resources doesn't load without it. Has the 'QB Core' error

**Comment by Holidayy95** [comment]
Also, the Submit button doesn't work anymore either since the update.

**Comment by Bigbearbeasttv** [comment]
The resource loads fine for me because he added local QBCore = exports['qb-core']:GetCoreObject() which replaced the import.lua. however I also have the submit button issue that you do.

**Comment by Holidayy95** [comment]
Yeah It seems to not give me the error now for the QB Core, weird. I do hope the Submit button breaking gets fixed tho

**Pull request closed without merging**
