### PR TITLE
Syntax error

### PR DESCRIPTION
**Pull request by Holidayy95**
Syntax error in line 200

### CODE REVIEW

**Comment by BerkieBb** [comment]
Just for the sake of my OCD, can you remove the space in between the SendNUIMessage and the table, I can't stand that because the other ones aren't like it

**Comment by Holidayy95** [comment]
uh the ones above it are like it, I think the one below is the only one without a space.

**Comment by Holidayy95** [comment]
but sure

**Comment by BerkieBb** [comment]
Oh I didn't notice that but thanks!

**Pull request merged**
